/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package streaming-commons-0.1.18 */
#define VERSION_streaming_commons "0.1.18"
#define MIN_VERSION_streaming_commons(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 18)

/* package array-0.5.1.1 */
#define VERSION_array "0.5.1.1"
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)

/* package async-2.1.1.1 */
#define VERSION_async "2.1.1.1"
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 1)

/* package base-4.9.1.0 */
#define VERSION_base "4.9.1.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  9 || \
  (major1) == 4 && (major2) == 9 && (minor) <= 1)

/* package blaze-builder-0.4.0.2 */
#define VERSION_blaze_builder "0.4.0.2"
#define MIN_VERSION_blaze_builder(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 0)

/* package bytestring-0.10.8.1 */
#define VERSION_bytestring "0.10.8.1"
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 8)

/* package directory-1.3.1.1 */
#define VERSION_directory "1.3.1.1"
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)

/* package network-2.6.3.2 */
#define VERSION_network "2.6.3.2"
#define MIN_VERSION_network(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 3)

/* package process-1.6.0.0 */
#define VERSION_process "1.6.0.0"
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 0)

/* package random-1.1 */
#define VERSION_random "1.1"
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)

/* package stm-2.4.4.1 */
#define VERSION_stm "2.4.4.1"
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  4 || \
  (major1) == 2 && (major2) == 4 && (minor) <= 4)

/* package text-1.2.2.2 */
#define VERSION_text "1.2.2.2"
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 2)

/* package transformers-0.5.4.0 */
#define VERSION_transformers "0.5.4.0"
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)

/* package unix-2.7.2.1 */
#define VERSION_unix "2.7.2.1"
#define MIN_VERSION_unix(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 2)

/* package zlib-0.6.1.2 */
#define VERSION_zlib "0.6.1.2"
#define MIN_VERSION_zlib(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)

/* tool alex-3.1.7 */
#define TOOL_VERSION_alex "3.1.7"
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 7)

/* tool gcc-5.4.0 */
#define TOOL_VERSION_gcc "5.4.0"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  4 || \
  (major1) == 5 && (major2) == 4 && (minor) <= 0)

/* tool ghc-8.0.2 */
#define TOOL_VERSION_ghc "8.0.2"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 2)

/* tool ghc-pkg-8.0.2 */
#define TOOL_VERSION_ghc_pkg "8.0.2"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 2)

/* tool haddock-2.17.3 */
#define TOOL_VERSION_haddock "2.17.3"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  17 || \
  (major1) == 2 && (major2) == 17 && (minor) <= 3)

/* tool happy-1.19.5 */
#define TOOL_VERSION_happy "1.19.5"
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 5)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.68.1 */
#define TOOL_VERSION_hsc2hs "0.68.1"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 1)

/* tool pkg-config-0.29.1 */
#define TOOL_VERSION_pkg_config "0.29.1"
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 1)

/* tool strip-2.26 */
#define TOOL_VERSION_strip "2.26"
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)

#define CURRENT_COMPONENT_ID "streaming-commons-0.1.18-8VOuc0FLneX8biv8PEXMEO"

#define CURRENT_PACKAGE_KEY "streaming-commons-0.1.18-8VOuc0FLneX8biv8PEXMEO"

