resolver: lts-2.22

packages:
- '.'

extra-deps:
- Cabal-1.18.1.5
- array-0.5.0.0
- base-4.7.0.2
- bin-package-db-0.0.0.0
- binary-0.7.1.0
- bytestring-0.10.4.0
- containers-0.5.5.1
- deepseq-1.3.0.2
- directory-1.2.1.0
- filepath-1.3.0.2
- ghc-7.8.4
- ghc-prim-0.3.1.0
- haskeline-0.7.1.2
- haskell2010-1.1.2.0
- haskell98-2.0.0.3
- hoopl-3.10.0.1
- hpc-0.6.0.1
- integer-gmp-0.5.1.0
- old-locale-1.0.0.6
- old-time-1.1.0.2
- pretty-1.1.1.1
- process-1.2.0.0
- rts-1.0
- template-haskell-2.9.0.0
- terminfo-0.4.0.0
- time-1.4.2
- transformers-0.3.0.0
- unix-2.7.0.1
- xhtml-3000.2.1


flags: {}

extra-package-dbs: []

